-- Database for Project
CREATE DATABASE IF NOT EXISTS DSMS;

-- Table for Employee Records
CREATE TABLE IF NOT EXISTS EMPLOYEE (
    ADMISSION_ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    GENDER CHAR(1),
    MARITAL_STATUS CHAR(1),
    SALARY INT,
    DOB DATE,
    HIRED_DATE DATE,
    PROFESSION VARCHAR(20)
);

-- Table for Wholesalers
CREATE TABLE IF NOT EXISTS WHOLESALERS (
    NAME VARCHAR(20),
    ADDRESS VARCHAR(80),
    CONTACT_NO CHAR(10),
    MAIL_ID VARCHAR(30),
    SUPPLY VARCHAR(20)
);

-- Table for Attendance Tracking
CREATE TABLE IF NOT EXISTS ATTENDANCE (
    NAME VARCHAR(30),
    DAYS_WORKING INT,
    DAYS_PRESENT INT,
    DAYS_ABSENT INT
);

-- Table for Stock Items
CREATE TABLE IF NOT EXISTS STOCKLIST (
    SNO CHAR(4) PRIMARY KEY,
    ITEM_NAME VARCHAR(50),
    PRICE FLOAT,
    TYPE VARCHAR(20)
);

-- Table to Track Stock Quantity
CREATE TABLE IF NOT EXISTS STOCKLIST_VOLUME (
    SNO CHAR(4) PRIMARY KEY,
    ITEM_NAME VARCHAR(50),
    PRICE FLOAT,
    TYPE VARCHAR(20),
    QUANTITY INT
);
